#!/usr/bin/env bash
echo " ||_____________________________________________________________________________________________________________||"
echo " ||  Welcome to                                                                                                 ||"
echo " ||       ____              __                                                                                  ||"
echo " ||      / __/__  ___ _____/ /__                                                                                ||" 
echo " ||     _\ \/ _ \/ _| / __/   _/                                                                                ||" 
echo " ||    /__ / .__/\_,_/_/ /_/\_\   version 2.1.0.cloudera1                                                       ||"
echo " ||       /_/                                                                                                   ||"
echo " || Using Python version 2.6.6 (r266:84292, Aug 18 2016 08:36:59)                                               ||"
echo " || SparkSession available as 'spark'.                                                                          ||"
echo " || >>> from os.path import expanduser, join, abspath                                                           ||"
echo " || >>> from pyspark.sql import SparkSession                                                                    ||"
echo " || >>> warehouse_location = abspath('hive/spark-warehouse')                                                    ||"
echo " || >>> spark = SparkSession.builder.appName(\"Python Spark SQL Hive session1\").config(\"spark.sql.warehouse.dir\", warehouse_location).enableHiveSupport().getOrCreate() ||"
echo " || >>> spark.sql(\"use staged_content\")                                                                         ||"
echo " || DataFrame[]                                                                                                 ||"
echo " || >>> spark.sql("show tables")                                                                                ||"
echo " || DataFrame[database: string, tableName: string, isTemporary: boolean]                                        ||"
echo " || >>> spark.sql(\"show tables\").show()                                                                         ||"
echo " || +--------------+--------------------+-----------+                                                           ||"
echo " || |      database|           tableName|isTemporary|                                                           ||"
echo " || +--------------+--------------------+-----------+                                                           ||"
echo " || |staged_content|analytics_frame_d...|      false|                                                           ||"
echo " || |staged_content|analytics_possesi...|      false|                                                           ||"
echo " || |staged_content|analytics_possesi...|      false|                                                           ||"
echo " || |staged_content|analytics_possesi...|      false|                                                           ||"
echo " || |staged_content|analytics_tracab_...|      false|                                                           ||"
echo " || |staged_content|analytics_tracab_...|      false|                                                           ||"
echo " || |staged_content|       nba_boxscores|      false|                                                           ||"
echo " || |staged_content|     pl_sequences_16|      false|                                                           ||"
echo " || |staged_content|         rc_tracking|      false|                                                           ||"
echo " || |staged_content|tracking_demo_sam...|      false|                                                           ||"
echo " || |staged_content|             xa_test|      false|                                                           ||"
echo " || +--------------+--------------------+-----------+                                                           ||"
echo " ||                                                                                                             ||"
echo " || >>> spark.sql(\"describe staged_content.rc_tracking\")                                                        ||"
echo " || DataFrame[col_name: string, data_type: string, comment: string]                                             ||"
echo " || >>> spark.sql(\"describe staged_content.rc_tracking\").show()                                                 ||"
echo " || +--------------------+---------+-------+                                                                    ||"
echo " || |            col_name|data_type|comment|                                                                    ||"
echo " || +--------------------+---------+-------+                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|   bigint|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|   bigint|   null|                                                                    ||"
echo " || |analytics_tracab_...|      int|   null|                                                                    ||"
echo " || |analytics_tracab_...|    float|   null|                                                                    ||"
echo " || |analytics_tracab_...|    float|   null|                                                                    ||"
echo " || |analytics_tracab_...|    float|   null|                                                                    ||"
echo " || |analytics_tracab_...|   string|   null|                                                                    ||"
echo " || +--------------------+---------+-------+                                                                    ||"
echo " ||                                                                                                             ||"
echo " || >>> spark.sql(\"describe staged_content.nba_boxscores\").show()                                               ||"
echo " || +-----------+---------+-------+                                                                             ||"
echo " || |   col_name|data_type|comment|                                                                             ||"
echo " || +-----------+---------+-------+                                                                             ||"
echo " || |     season|   string|   null|                                                                             ||"
echo " || | boxscoreid|   string|   null|                                                                             ||"
echo " || |       date|   string|   null|                                                                             ||"
echo " || |       time|   string|   null|                                                                             ||"
echo " || |      venue|   string|   null|                                                                             ||"
echo " || |       road|   string|   null|                                                                             ||"
echo " || |  road_uuid|   string|   null|                                                                             ||"
echo " || | road_score|      int|   null|                                                                             ||"
echo " || |       home|   string|   null|                                                                             ||"
echo " || |  home_uuid|   string|   null|                                                                             ||"
echo " || | home_score|      int|   null|                                                                             ||"
echo " || |       team|   string|   null|                                                                             ||"
echo " || |  team_uuid|   string|   null|                                                                             ||"
echo " || |    starter|  boolean|   null|                                                                             ||"
echo " || |      bench|  boolean|   null|                                                                             ||"
echo " || |     player|   string|   null|                                                                             ||"
echo " || |   playerid|   string|   null|                                                                             ||"
echo " || |player_uuid|   string|   null|                                                                             ||"
echo " || |        min|   string|   null|                                                                             ||"
echo " || |        fgm|      int|   null|                                                                             ||"
echo " || +-----------+---------+-------+                                                                             ||"
echo " || only showing top 20 rows                                                                                    ||"
echo " ||                                                                                                             ||"
echo " || >>> exit()                                                                                                  ||"
echo " ||_____________________________________________________________________________________________________________||"

# PySpark2 with Additional JARS
pyspark2 --master yarn --deploy-mode client --jars ./commons-csv-1.1.jar,./spark-csv_2.11-1.5.0.jar

echo "   --  .Done.  1 more smile.  :) " 
