#!/usr/bin/env bash
echo " ||_____________________________________________________________________________________________________________||"
echo " ||  Welcome to                                                                                                 ||"
echo " ||       ____              __                                                                                  ||"
echo " ||      / __/__  ___ _____/ /__                                                                                ||" 
echo " ||     _\ \/ _ \/ _| / __/   _/                                                                                ||" 
echo " ||    /__ / .__/\_,_/_/ /_/\_\   version 2.1.0.cloudera1                                                       ||"
echo " ||       /_/                                                                                                   ||"
echo " ||                                                                                                             ||"
echo " || Using Python version 2.6.6 (r266:84292, Aug 18 2016 08:36:59)                                               ||"
echo " || SparkSession available as 'spark'.                                                                          ||"
echo " || >>> nba_fn = \"data/raw/content/analytics/basketball/sample/0021500492.json\"                                 ||"
echo " || >>> nda_file = spark.read.json(nba_fn)                                                                      ||"
echo " || 17/07/17 10:56:28 WARN datasources.DataSource: Error while looking for metadata directory.                  ||"
echo " || >>> nda_file.printSchema()                                                                                  ||"
echo " || root                                                                                                        ||"
echo " ||  |-- events: array (nullable = true)                                                                        ||"
echo " ||  |    |-- element: struct (containsNull = true)                                                             ||"
echo " ||  |    |    |-- eventId: string (nullable = true)                                                            ||"
echo " ||  |    |    |-- home: struct (nullable = true)                                                               ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||" 
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |    |    |-- moments: array (nullable = true)                                                             ||"
echo " ||  |    |    |    |-- element: array (containsNull = true)                                                    ||"
echo " ||  |    |    |    |    |-- element: string (containsNull = true)                                              ||"
echo " ||  |    |    |-- visitor: struct (nullable = true)                                                            ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||" 
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |-- gamedate: string (nullable = true)                                                                     ||"
echo " ||  |-- gameid: string (nullable = true)                                                                       ||"
echo " ||                                                                                                             ||"
echo " || >>> nda_file.count()                                                                                        ||"
echo " || 1                                                                                                           ||"
echo " || >>>                                                                                                         ||"
echo " || >>> nda_file.write.format(\"parquet\").save(\"data/raw/content/analytics/basketball/parquet/file.parquet\")     ||"
echo " || >>> df2 = spark.read.parquet(\"data/raw/content/analytics/basketball/parquet/file.parquet\")                  ||"
echo " || >>> df2.printSchema()                                                                                       ||"
echo " || root                                                                                                        ||"
echo " ||  |-- events: array (nullable = true)                                                                        ||" 
echo " ||  |    |-- element: struct (containsNull = true)                                                             ||"
echo " ||  |    |    |-- eventId: string (nullable = true)                                                            ||"
echo " ||  |    |    |-- home: struct (nullable = true)                                                               ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |    |    |-- moments: array (nullable = true)                                                             ||"
echo " ||  |    |    |    |-- element: array (containsNull = true)                                                    ||"
echo " ||  |    |    |    |    |-- element: string (containsNull = true)                                              ||"
echo " ||  |    |    |-- visitor: struct (nullable = true)                                                            ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |-- gamedate: string (nullable = true)                                                                     ||"
echo " ||  |-- gameid: string (nullable = true)                                                                       ||"
echo " ||                                                                                                             ||"
echo " || >>> df2.count()                                                                                             ||"
echo " ||  1                                                                                                          ||"
echo " || >>>                                                                                                         ||"
echo " || >>> quit()                                                                                                  ||"
echo " || >>> >>> nba_parquet = \"data/raw/content/analytics/basketball/parquet/file.parquet\"                          ||"
echo " || >>> nba_file = spark.read.parquet(nba_parquet)                                                              ||"
echo " || >>> nba_file.printSchema()                                                                                  ||"
echo " || root                                                                                                        ||"
echo " ||  |-- events: array (nullable = true)                                                                        ||"
echo " ||  |    |-- element: struct (containsNull = true)                                                             ||"
echo " ||  |    |    |-- eventId: string (nullable = true)                                                            ||"
echo " ||  |    |    |-- home: struct (nullable = true)                                                               ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |    |    |-- moments: array (nullable = true)                                                             ||"
echo " ||  |    |    |    |-- element: array (containsNull = true)                                                    ||"
echo " ||  |    |    |    |    |-- element: string (containsNull = true)                                              ||"
echo " ||  |    |    |-- visitor: struct (nullable = true)                                                            ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |-- gamedate: string (nullable = true)                                                                     ||"
echo " ||  |-- gameid: string (nullable = true)                                                                       ||"
echo " ||                                                                                                             ||"
echo " || >>> nba_file.createOrReplaceTempView(\"nba_parquet_view\")                                                    ||"
echo " || >>> nba_events= spark.sql(\"select events from nba_parquet_view where events IS NOT NULL and gamedate IS NOT NULL and gameid IS NOT  NULL\")   ||" 
echo " || >>> nba_events.count()                                                                                      ||"
echo " || 1                                                                                                           ||"
echo " || >>> nba_events.printSchema()                                                                                ||"
echo " || root                                                                                                        ||"
echo " ||  |-- events: array (nullable = true)                                                                        ||"
echo " ||  |    |-- element: struct (containsNull = true)                                                             ||"
echo " ||  |    |    |-- eventId: string (nullable = true)                                                            ||"
echo " ||  |    |    |-- home: struct (nullable = true)                                                               ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||  |    |    |-- moments: array (nullable = true)                                                             ||"
echo " ||  |    |    |    |-- element: array (containsNull = true)                                                    ||"
echo " ||  |    |    |    |    |-- element: string (containsNull = true)                                              ||"
echo " ||  |    |    |-- visitor: struct (nullable = true)                                                            ||"
echo " ||  |    |    |    |-- abbreviation: string (nullable = true)                                                  ||"
echo " ||  |    |    |    |-- name: string (nullable = true)                                                          ||"
echo " ||  |    |    |    |-- players: array (nullable = true)                                                        ||"
echo " ||  |    |    |    |    |-- element: struct (containsNull = true)                                              ||"
echo " ||  |    |    |    |    |    |-- firstname: string (nullable = true)                                           ||"
echo " ||  |    |    |    |    |    |-- jersey: string (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- lastname: string (nullable = true)                                            ||"
echo " ||  |    |    |    |    |    |-- playerid: long (nullable = true)                                              ||"
echo " ||  |    |    |    |    |    |-- position: string (nullable = true)                                            ||"
echo " ||  |    |    |    |-- teamid: long (nullable = true)                                                          ||"
echo " ||                                                                                                             ||"
echo " || >>> from pyspark.sql import functions as fnd                                                                ||"
echo " || >>> nba_events.select(fnd.explode((\"events\")))                                                              ||"
echo " || DataFrame[col: struct<eventId:string,home:struct<abbreviation:string,name:string,players:array<struct<firstname:string,jersey:string,lastname:string,playerid:bigint,position:string>>,teamid:bigint>,moments:array<array<string>>,visitor:struct<abbreviation:string,name:string,players:array<struct<firstname:string,jersey:string,lastname:string,playerid:bigint,position:string>>,teamid:bigint>>]                                                                ||"
echo " || >>> nba_events.select(fnd.explode((\"events\"))).take(1)                                                      ||"
echo " || [Row(col=Row(eventId=u'1', home=Row(abbreviation=u'TOR', name=u'Toronto Raptors', players=[Row(firstname=u'James', jersey=u'3', lastname=u'Johnson', playerid=201949, position=u'F'), Row(firstname=u'Luis', jersey=u'4', lastname=u'Scola', playerid=2449, position=u'F'), Row(firstname=u'DeMarre', jersey=u'5', lastname=u'Carroll', playerid=201960, position=u'F'), Row(firstname=u'Cory', jersey=u'6', lastname=u'Joseph', playerid=202709, position=u'G'), Row(firstname=u'Kyle', jersey=u'7', lastname=u'Lowry', playerid=200768, position=u'G'), Row(firstname=u'Bismack', jersey=u'8', lastname=u'Biyombo', playerid=202687, position=u'C-F'), ... ||"
echo " || >>>                                                                                                         ||"
echo " || >>> quit()                                                                                                  ||"
echo " ||_____________________________________________________________________________________________________________||"

# PySpark2 with Additional JARS
pyspark2 --master yarn --deploy-mode client --jars ./commons-csv-1.1.jar,./spark-csv_2.11-1.5.0.jar

echo "   --  .Done.  --   -_._- " 
