CREATE TABLE "MOVIEDEMO"."VDP_EVENTS"
  (
    "EVENT_ID" NUMBER(10,0),
    "DESCRIPTION" NVARCHAR2(1000) NOT NULL ENABLE,
    "RIGHTS_ID" NUMBER(10,0) NOT NULL ENABLE,
    "FEED_START_TIME" TIMESTAMP (6),
    "FEED_END_TIME" TIMESTAMP (6),
    "EVENT_START_TIME" TIMESTAMP (6),
    "EVENT_END_TIME" TIMESTAMP (6),
    "FEED_INFO"     VARCHAR2(1000 BYTE),
    "STATUS"        VARCHAR2(10 BYTE) DEFAULT 'PROPOSED' NOT NULL ENABLE,
    "GEOBLOCK_ID"   NUMBER(10,0),
    "CHANNEL_ID"    NUMBER(10,0),
    "JOB_ID"        VARCHAR2(1020 BYTE),
    "EXTERNAL_URL"  VARCHAR2(200 BYTE),
    "BACKUP_JOB_ID" VARCHAR2(1020 BYTE),
    "COMMENTATORS_NAMES" NVARCHAR2(255),
    "COMMENTATORS_PHONE_NUMBER" VARCHAR2(20 BYTE),
    "COMMENTATORS_EMAIL"        VARCHAR2(100 BYTE),
    "VOICE_OVER_BOOTH"          NUMBER(10,0),
    "CONTACT_ID"                NUMBER(10,0),
    "REPORTS_PROC_STATUS"       VARCHAR2(64 BYTE),
    "LOCATION" NVARCHAR2(255),
    "ENCODER_OPTION_ID"      NUMBER(10,0),
    "BROADCASTMANAGER_EVENT" CHAR(1 BYTE),
    "NO_OF_MATCHES"          NUMBER(*,0),
    "UUID"                   VARCHAR2(36 BYTE),
    "REPORTS2_PROC_STATUS"   VARCHAR2(64 BYTE) DEFAULT 'NOT_PROCESSED' NOT NULL ENABLE,
    "REPORTS2_PROC_PRIORITY" NUMBER(2,0) DEFAULT 20 NOT NULL ENABLE,
    "PROD_TIER_ID"           NUMBER(10,0),
    CONSTRAINT "VDP_EVENTS_PK" PRIMARY KEY ("EVENT_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "MOVIEDEMO" ENABLE
    
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "MOVIEDEMO" ;
  
COMMENT ON COLUMN "MOVIEDEMO"."VDP_EVENTS"."NO_OF_MATCHES"
IS
  'Specifies the completed number of matches present in the Event';
  COMMENT ON COLUMN "MOVIEDEMO"."VDP_EVENTS"."REPORTS2_PROC_STATUS"
IS
  'The reporting 2.0 status of the event';
  COMMENT ON COLUMN "MOVIEDEMO"."VDP_EVENTS"."REPORTS2_PROC_PRIORITY"
IS
  'Used by prioritization mechanism (10 = high priority, 20 = normal priority, 30 = low priority)';
  COMMENT ON COLUMN "MOVIEDEMO"."VDP_EVENTS"."PROD_TIER_ID"
IS
  'ID of the MOVIEDEMO.VDP_PROD_TIER table';
  
  CREATE INDEX "MOVIEDEMO"."CHANNEL_ID_IDX" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "CHANNEL_ID"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
    
  CREATE INDEX "MOVIEDEMO"."VDP_EVENTS_EVENT_END_IDX" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "EVENT_END_TIME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
  CREATE INDEX "MOVIEDEMO"."VDP_EVENTS_EVENT_START_IDX" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "EVENT_START_TIME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
  CREATE INDEX "MOVIEDEMO"."VDP_EVENTS_FEED_END_IDX" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "FEED_END_TIME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
  CREATE INDEX "MOVIEDEMO"."VDP_EVENTS_FEED_START_IDX" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "FEED_START_TIME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
  CREATE INDEX "MOVIEDEMO"."VDP_EVENTS_IND2" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "FEED_END_TIME",
      "EVENT_ID",
      "ENCODER_OPTION_ID"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
CREATE UNIQUE INDEX "MOVIEDEMO"."VDP_EVENTS_PK" ON "MOVIEDEMO"."VDP_EVENTS"
  (
    "EVENT_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "MOVIEDEMO" ;
  CREATE INDEX "MOVIEDEMO"."VDP_EVENTS_RID_FST" ON "MOVIEDEMO"."VDP_EVENTS"
    (
      "RIGHTS_ID",
      "FEED_START_TIME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "MOVIEDEMO" ;
