  CREATE TABLE "MOVIEDEMO"."VDP_EVENTS_HIVE" 
   (	"EVENT_ID" NUMBER(10,0), 
	"DESCRIPTION" NVARCHAR2(1000) NOT NULL ENABLE, 
	"RIGHTS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FEED_START_TIME" TIMESTAMP (6), 
	"FEED_END_TIME" TIMESTAMP (6), 
	"EVENT_START_TIME" TIMESTAMP (6), 
	"EVENT_END_TIME" TIMESTAMP (6), 
	"FEED_INFO" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'PROPOSED' NOT NULL ENABLE, 
	"GEOBLOCK_ID" NUMBER(10,0), 
	"CHANNEL_ID" NUMBER(10,0), 
	"JOB_ID" VARCHAR2(1020 BYTE), 
	"EXTERNAL_URL" VARCHAR2(200 BYTE), 
	"BACKUP_JOB_ID" VARCHAR2(1020 BYTE), 
	"COMMENTATORS_NAMES" NVARCHAR2(255), 
	"COMMENTATORS_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"COMMENTATORS_EMAIL" VARCHAR2(100 BYTE), 
	"VOICE_OVER_BOOTH" NUMBER(10,0), 
	"CONTACT_ID" NUMBER(10,0), 
	"REPORTS_PROC_STATUS" VARCHAR2(64 BYTE), 
	"LOCATION" NVARCHAR2(255), 
	"ENCODER_OPTION_ID" NUMBER(10,0), 
	"BROADCASTMANAGER_EVENT" CHAR(1 BYTE), 
	"NO_OF_MATCHES" NUMBER(*,0), 
	"UUID" VARCHAR2(36 BYTE)
  ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_HIVE
      DEFAULT DIRECTORY "ORA_BIGDATA_CL_bigdatalite"
      ACCESS PARAMETERS
      ( com.oracle.bigdata.tablename: published_vdp.vdp_events 
      )
      LOCATION
       ( 
         ''
       )
    );